---
title: "Infographic Code"
output: html_document
date: "2024-11-25"
---

Dylan Vander Sanden, Eden Larson, Matteo Magcalas, Sophia Rogers, Susan Orea-Zarate

```{r, echo = FALSE}
knitr::opts_chunk$set(warnings = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(lubridate)
```

```{r}
#read dataset into RStudio
nba3pt <- read_csv("nba3pt.csv")

nba3pt <- nba3pt %>% 
  mutate(`3P_pct` = `3PM` / `3PA`)

head(nba3pt)
```

```{r}
bw3pt <- nba3pt %>% 
  group_by(Season) %>% 
  summarize(
    worstTeam = Team[which.min(W)],
    minW = min(W),
    worstTeam3PM = `3PM`[which.min(W)],
    worstTeam3PA = `3PA`[which.min(W)],
    worstTeam3P_pct = `3P_pct`[which.min(W)],
    championTeam = Team[`Playoff Result` == "Champions"],
    championW = W[`Playoff Result` == "Champions"],
    championTeam3PM = `3PM`[`Playoff Result` == "Champions"],
    championTeam3PA = `3PA`[`Playoff Result` == "Champions"],
    championTeam3P_pct = `3P_pct`[`Playoff Result` == "Champions"]
  )

head(bw3pt)
```

```{r}
#Graph 1
avg3PA_dt <- nba3pt %>% 
  group_by(Season) %>% 
  summarize(avg3PA = mean(`3PA`))

plot1 <- ggplot(avg3PA_dt, aes(x = Season, y = avg3PA)) +
  geom_bar(stat = "identity", fill = "darkblue") +
  labs(
    title = "Average Three-Point Attempts (2014-2024)",
    x = "Season",
    y = "Average 3PA"
  ) +
  coord_cartesian(ylim = c(20, 35)) +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = 'transparent', color = NA), # Transparent panel
    plot.background = element_rect(fill = 'transparent', color = NA), # Transparent plot
    panel.grid.major = element_blank(), # Remove major gridlines
    panel.grid.minor = element_blank(), # Remove minor gridlines
    legend.background = element_rect(fill = 'transparent', color = NA), # Transparent legend
    legend.box.background = element_rect(fill = 'transparent', color = NA), # Transparent legend box
    text = element_text(color = "darkblue"), # White text
    axis.text.x = element_text(angle = 45, hjust = 1, color = "darkblue"), # White x-axis text
    axis.text.y = element_text(color = "darkblue"), # White y-axis text
    axis.title.y = element_text(color = "darkblue"), # White y-axis title
    legend.title = element_text(color = "darkblue"), # White legend title
    legend.text = element_text(color = "darkblue"), # White legend text
    plot.title = element_text(color = "darkblue", hjust = 0.5) # White and centered plot title
  )

plot1
# Save the plot with a transparent background, uncomment and run code below to save graph as png file
ggsave("graph1.png", plot = plot1, bg = "transparent", width = 8, height = 6, dpi = 300)
```

```{r}
#Graph 2
# Convert Season to numeric or ordered
bos_3pt <- nba3pt %>%
  filter(Team == "Boston Celtics") %>%
  mutate(Season = as.numeric(sub("-.*", "", Season))) %>% # Convert to start year as numeric
  select(Season, `3PA`, `3PM`)

# Plotting the data
plot2 <- ggplot(bos_3pt, aes(x = Season)) +
  geom_line(aes(y = `3PA`, color = "3PA (Attempts)"), size = 1.2) +
  geom_line(aes(y = `3PM`, color = "3PM (Makes)"), size = 1.2) +
  geom_point(aes(y = `3PA`, color = "3PA (Attempts)"), size = 3) +
  geom_point(aes(y = `3PM`, color = "3PM (Makes)"), size = 3) +
  scale_color_manual(values = c("3PA (Attempts)" = "darkblue", "3PM (Makes)" = "darkred")) +
  labs(
    title = "Boston Celtics: 3-Point Shooting Over 10 Seasons",
    x = "Season",
    y = "3-Point Shots",
    color = "Legend"
  ) +
  scale_x_continuous(breaks = unique(bos_3pt$Season)) + # Ensure all seasons are displayed
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = 'transparent', color = NA), # Transparent panel
    plot.background = element_rect(fill = 'transparent', color = NA), # Transparent plot
    panel.grid.major = element_blank(), # Remove major gridlines
    panel.grid.minor = element_blank(), # Remove minor gridlines
    legend.background = element_rect(fill = 'transparent', color = NA), # Transparent legend
    legend.box.background = element_rect(fill = 'transparent', color = NA), # Transparent legend box
    text = element_text(color = "darkblue"), # White text
    axis.text.x = element_text(angle = 45, hjust = 1, color = "darkblue"), # White x-axis text
    axis.text.y = element_text(color = "darkblue"), # White y-axis text
    axis.title.x = element_text(color = "darkblue"), # White x-axis title
    axis.title.y = element_text(color = "darkblue"), # White y-axis title
    legend.title = element_text(color = "darkblue"), # White legend title
    legend.text = element_text(color = "darkblue"), # White legend text
    plot.title = element_text(color = "darkblue", hjust = 0.5) # White and centered plot title
  )


plot2
# Save the plot with a transparent background, uncomment and run code below to save graph as png file
ggsave("graph2.png", plot = plot2, bg = "transparent", width = 8, height = 6, dpi = 300)
```

```{r}
#Graph 3a: 3PA
bw3pt_long_3pa <- bw3pt %>%
  dplyr::select(Season, worstTeam3PA, championTeam3PA) %>%
  tidyr::pivot_longer(cols = c(worstTeam3PA, championTeam3PA),
                      names_to = "Team_Type",
                      values_to = "Three_Point_Attempts") %>%
  dplyr::mutate(Team_Type = dplyr::recode(Team_Type, 
                             worstTeam3PA = "Worst Team", 
                             championTeam3PA = "Champion Team"))
# Create the plot
plot3a <- ggplot(bw3pt_long_3pa, aes(x = Season, y = Three_Point_Attempts, fill = Team_Type)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(
    values = c("Champion Team" = "darkblue", # White for champions
               "Worst Team" = "darkred")   # Cyan for the worst team
  ) +
  labs(
    title = "Comparison of 3PA: Worst Team vs Champion Team",
    x = "Season",
    y = "3-Point Attempts",
    fill = "Team Type"
  ) +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = 'transparent', color = NA), # Transparent panel
    plot.background = element_rect(fill = 'transparent', color = NA), # Transparent plot
    panel.grid.major = element_blank(), # Remove major gridlines
    panel.grid.minor = element_blank(), # Remove minor gridlines
    legend.background = element_rect(fill = 'transparent', color = NA), # Transparent legend
    legend.box.background = element_rect(fill = 'transparent', color = NA), # Transparent legend box
    text = element_text(color = "darkblue"), # White text
    axis.text.x = element_text(angle = 45, hjust = 1, color = "darkblue"), # White x-axis text
    axis.text.y = element_text(color = "darkblue"), # White y-axis text
    axis.title.x = element_text(color = "darkblue"), # White x-axis title
    axis.title.y = element_text(color = "darkblue"), # White y-axis title
    legend.title = element_text(color = "darkblue"), # White legend title
    legend.text = element_text(color = "darkblue"), # White legend text
    plot.title = element_text(color = "darkblue", hjust = 0.5) # White and centered plot title
  )

plot3a
# Save the plot with a transparent background, uncomment and run code below to save graph as png file
ggsave("graph3a.png", plot = plot3a, bg = "transparent", width = 8, height = 6, dpi = 300)
```

```{r}
#Graph 3b: 3P%
bw3pt_long_pct <- bw3pt %>%
  dplyr::select(Season, worstTeam3P_pct, championTeam3P_pct) %>%
  tidyr::pivot_longer(cols = c(worstTeam3P_pct, championTeam3P_pct),
                      names_to = "Team_Type",
                      values_to = "Three_Point_Percent") %>%
  dplyr::mutate(Team_Type = dplyr::recode(Team_Type, 
                             worstTeam3P_pct = "Worst Team", 
                             championTeam3P_pct = "Champion Team"))

plot3b <- ggplot(bw3pt_long_pct, aes(x = Season, y = Three_Point_Percent, fill = Team_Type)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(
    values = c("Champion Team" = "darkblue", # White for champions
               "Worst Team" = "darkred")   # Cyan for the worst team
  ) +
  labs(
    title = "Comparison of 3PT%: Worst Team vs Champion Team",
    x = "Season",
    y = "3-Point Percentage",
    fill = "Team Type"
  ) +
  coord_cartesian(ylim = c(0.3, 0.4)) + 
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = 'transparent', color = NA), # Transparent panel
    plot.background = element_rect(fill = 'transparent', color = NA), # Transparent plot
    panel.grid.major = element_blank(), # Remove major gridlines
    panel.grid.minor = element_blank(), # Remove minor gridlines
    legend.background = element_rect(fill = 'transparent', color = NA), # Transparent legend
    legend.box.background = element_rect(fill = 'transparent', color = NA), # Transparent legend box
    text = element_text(color = "darkblue"), # White text
    axis.text.x = element_text(angle = 45, hjust = 1, color = "darkblue"), # White x-axis text
    axis.text.y = element_text(color = "darkblue"), # White y-axis text
    axis.title.x = element_text(color = "darkblue"), # White x-axis title
    axis.title.y = element_text(color = "darkblue"), # White y-axis title
    legend.title = element_text(color = "darkblue"), # White legend title
    legend.text = element_text(color = "darkblue"), # White legend text
    plot.title = element_text(color = "darkblue", hjust = 0.5) # White and centered plot title
  )

plot3b
# Save the plot with a transparent background, uncomment and run code below to save graph as png file
ggsave("graph3b.png", plot = plot3b, bg = "transparent", width = 8, height = 6, dpi = 300)
```


```{r, fig.width = 6, fig.height = 10}
nba_att_avgs <- nba3pt %>% 
  group_by(Season) %>% 
  summarize(avgpct2PA = (mean(FGA) - mean(`3PA`)) / mean(FGA),
            avgpct3PA = mean(`3PA`) / mean(FGA))

nba_long <- nba_att_avgs %>% 
  pivot_longer(cols = c(avgpct2PA, avgpct3PA), 
               names_to = "ShotType", values_to = "Percentage")

plot4 <- ggplot(nba_long, aes(y = reorder(Season, desc(Season)), x = Percentage, fill = ShotType)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = c("avgpct2PA" = "darkblue", "avgpct3PA" = "darkred"), 
                    labels = c("2-Point FG%", "3-Point FG%")) +
  labs(title = "NBA Field Goal Attempt Distribution by Season",
       x = "Percentage of FG Attempts", y = "Season",
       fill = "Shot Type") +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = 'transparent', color = NA), # Transparent panel
    plot.background = element_rect(fill = 'transparent', color = NA), # Transparent plot
    panel.grid.major = element_blank(), # Remove major gridlines
    panel.grid.minor = element_blank(), # Remove minor gridlines
    legend.background = element_rect(fill = 'transparent', color = NA), # Transparent legend
    legend.box.background = element_rect(fill = 'transparent', color = NA), # Transparent legend box
    text = element_text(color = "darkblue"), # White text
    axis.text.x = element_text(angle = 45, hjust = 1, color = "darkblue"), # White x-axis text
    axis.text.y = element_text(color = "darkblue"), # White y-axis text
    axis.title.x = element_text(color = "darkblue"), # White x-axis title
    axis.title.y = element_text(color = "darkblue"), # White y-axis title
    legend.title = element_text(color = "darkblue"), # White legend title
    legend.text = element_text(color = "darkblue"), # White legend text
    plot.title = element_text(color = "darkblue", hjust = 0.5) # White and centered plot title
  )

plot4
# Save the plot with a transparent background, uncomment and run code below to save graph as png file
ggsave("graph4.png", plot = plot4, bg = "transparent", width = 6, height = 10, dpi = 300)
```
```{r}
nba3pt
```


```{r}
nba3pt %>% 
  group_by(Season, Team) %>% 
  summarize(pct3PA = `3PA`/FGA)
```